"""add unique project membership constraint

Revision ID: 35db572bdb82
Revises: f4e727f11500
Create Date: 2026-10-07 10:33:39.605060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35db572bdb82'
down_revision: Union[str, Sequence[str], None] = 'f4e727f11500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_project_members_project_user', 'project_members', ['project_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_members_project_user', 'project_members', type_='unique')
    # ### end Alembic commands ###
